// CV Analysis Service - Business Logic Layer

import { CVAnalysisRepository } from "@/repositories/cv-analysis.repository.js";
import { FileProcessingService } from "./file-processing.service.js";
import type { CVAnalysisRequest, CVAnalysisResult } from "@/types/ai.types.js";

export interface ICVAnalysisService {
  analyzeCV(request: CVAnalysisRequest): Promise<CVAnalysisResult>;
  validateRequest(request: CVAnalysisRequest): boolean;
  enrichRequest(request: CVAnalysisRequest): CVAnalysisRequest;
}

export class CVAnalysisService implements ICVAnalysisService {
  private repository: CVAnalysisRepository;
  private fileProcessingService: FileProcessingService;

  constructor() {
    this.repository = new CVAnalysisRepository();
    this.fileProcessingService = new FileProcessingService();
  }

  /**
   * Analyze CV
   */
  async analyzeCV(request: CVAnalysisRequest): Promise<CVAnalysisResult> {
    console.log("🔍 [CV Service] Starting CV analysis:", {
      userId: request.userId,
      hasCvText: !!request.cvText,
      hasCvFile: !!request.cvFile,
      jobRequirementsLength: request.jobRequirements.length,
      timestamp: new Date().toISOString(),
    });

    // Validate request
    if (!this.validateRequest(request)) {
      console.log("❌ [CV Service] Request validation failed");
      throw new Error("Invalid CV analysis request");
    }
    console.log("✅ [CV Service] Request validation passed");

    // Process CV input (text or file)
    const cvText = await this.processCVInput(request);
    console.log("📝 [CV Service] CV text processed, length:", cvText.length);

    // Create enriched request with processed CV text
    const enrichedRequest = this.enrichRequest({
      ...request,
      cvText,
    });
    console.log("🔧 [CV Service] Request enriched");

    try {
      console.log("⚙️ [CV Service] Calling repository to analyze CV...");
      // Analyze CV using repository
      const result = await this.repository.analyzeCV(enrichedRequest);

      console.log("📊 [CV Service] Repository returned result:", {
        hasResult: !!result,
        score: result?.score,
        matchPercentage: result?.matchPercentage,
        resultKeys: result ? Object.keys(result) : [],
        fullResult: JSON.stringify(result, null, 2),
      });

      // Validate generated result
      if (!result) {
        console.log("❌ [CV Service] No result generated by repository");
        throw new Error("No CV analysis was generated");
      }

      // Validate score ranges
      if (result.score < 0 || result.score > 100) {
        console.warn(
          `CV analysis score out of range: ${result.score}, normalizing to 0-100`
        );
        result.score = Math.max(0, Math.min(100, result.score));
      }

      if (result.matchPercentage < 0 || result.matchPercentage > 100) {
        console.warn(
          `CV analysis match percentage out of range: ${result.matchPercentage}, normalizing to 0-100`
        );
        result.matchPercentage = Math.max(
          0,
          Math.min(100, result.matchPercentage)
        );
      }

      return result;
    } catch (error) {
      console.error("CV analysis service error:", error);
      throw error;
    }
  }

  /**
   * Process CV input (text or file) and return extracted text
   */
  private async processCVInput(request: CVAnalysisRequest): Promise<string> {
    // If CV text is provided directly, use it
    if (request.cvText && request.cvText.trim().length > 0) {
      console.log("📝 [CV Service] Using provided CV text");
      return request.cvText.trim();
    }

    // If CV file is provided, process it to extract text
    if (request.cvFile) {
      console.log(
        "📁 [CV Service] Processing CV file:",
        request.cvFile.originalname
      );

      const fileResult = await this.fileProcessingService.processCVFile(
        request.cvFile
      );

      if (!fileResult.success) {
        throw new Error(`Failed to process CV file: ${fileResult.error}`);
      }

      if (fileResult.extractedText.trim().length < 50) {
        throw new Error(
          "Extracted text from CV file is too short for meaningful analysis (minimum 50 characters)"
        );
      }

      console.log("✅ [CV Service] Successfully extracted text from CV file");
      return fileResult.extractedText.trim();
    }

    throw new Error("Either cvText or cvFile must be provided");
  }

  /**
   * Validate the CV analysis request
   */
  validateRequest(request: CVAnalysisRequest): boolean {
    // Must have either CV text or CV file
    if (
      (!request.cvText || request.cvText.trim().length === 0) &&
      !request.cvFile
    ) {
      return false;
    }

    if (
      !request.jobRequirements ||
      request.jobRequirements.trim().length === 0
    ) {
      return false;
    }

    if (!request.userId || request.userId.trim().length === 0) {
      return false;
    }

    // If CV text is provided, check minimum length
    if (request.cvText && request.cvText.trim().length < 50) {
      return false;
    }

    if (request.jobRequirements.trim().length < 20) {
      return false;
    }

    return true;
  }

  /**
   * Enrich request with default values and validation
   */
  enrichRequest(request: CVAnalysisRequest): CVAnalysisRequest {
    return {
      cvText: request.cvText!.trim(), // We know cvText exists here since we processed it
      jobRequirements: request.jobRequirements.trim(),
      userId: request.userId.trim(),
    };
  }

  /**
   * Get estimated processing time based on request complexity
   */
  getEstimatedProcessingTime(request: CVAnalysisRequest): number {
    // Base time: 20 seconds
    let estimatedTime = 20;

    // Add time for complex requests
    if (request.cvText && request.cvText.length > 2000) estimatedTime += 10;
    if (request.cvText && request.cvText.length > 5000) estimatedTime += 15;
    if (request.jobRequirements.length > 500) estimatedTime += 5;
    if (request.jobRequirements.length > 1000) estimatedTime += 10;

    // Add extra time for file processing
    if (request.cvFile) {
      estimatedTime += 15; // Additional time for OCR/PDF processing
    }

    return estimatedTime;
  }

  /**
   * Extract key information from CV text for quick assessment
   */
  extractCVSummary(cvText: string): {
    estimatedExperience: number;
    keySkills: string[];
    educationLevel: string;
  } {
    const text = cvText.toLowerCase();

    // Estimate experience based on keywords
    let estimatedExperience = 0;
    if (
      text.includes("senior") ||
      text.includes("lead") ||
      text.includes("manager")
    ) {
      estimatedExperience = 5;
    } else if (text.includes("mid") || text.includes("intermediate")) {
      estimatedExperience = 3;
    } else if (text.includes("junior") || text.includes("entry")) {
      estimatedExperience = 1;
    }

    // Extract common skills
    const commonSkills = [
      "javascript",
      "python",
      "java",
      "react",
      "node.js",
      "sql",
      "aws",
      "docker",
      "agile",
      "scrum",
      "git",
      "html",
      "css",
      "typescript",
      "angular",
      "vue",
    ];
    const keySkills = commonSkills.filter((skill) => text.includes(skill));

    // Determine education level
    let educationLevel = "bachelor";
    if (text.includes("phd") || text.includes("doctorate")) {
      educationLevel = "phd";
    } else if (text.includes("master") || text.includes("mba")) {
      educationLevel = "master";
    } else if (text.includes("associate") || text.includes("diploma")) {
      educationLevel = "associate";
    }

    return {
      estimatedExperience,
      keySkills,
      educationLevel,
    };
  }
}
